name: Run Custom Script and Archive Artifacts

# Trigger workflow manually via GitHub UI
on:
  workflow_dispatch:

jobs:
  run-script-and-artifact:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      # Step 3: Install the dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          python -m pip install -r requirements.txt

      # Step 4: Run the main script
      - name: Run the main script
        run: |
          python main.py

      # Step 5: Archive the artifact folder
      - name: Upload Artifact
        if: success()  # Only upload if the script runs successfully
        uses: actions/upload-artifact@v3
        with:
          name: artifact-folder
          path: output/  # Replace 'artifact/' with the actual path of your artifact folder
